/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Account,
    AccountFromJSON,
    AccountToJSON,
} from '../models/Account';
import {
    type Balance,
    BalanceFromJSON,
    BalanceToJSON,
} from '../models/Balance';
import {
    type TransactionPage,
    TransactionPageFromJSON,
    TransactionPageToJSON,
} from '../models/TransactionPage';

export interface GetBalancesRequest {
    consentId: string;
    accountId: string;
}

export interface GetTransactionsRequest {
    consentId: string;
    accountId: string;
    pageKey?: string;
    pageSize?: number;
}

export interface ListAccountsRequest {
    consentId: string;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getBalances without sending the request
     */
    async getBalancesRequestOpts(requestParameters: GetBalancesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['consentId'] == null) {
            throw new runtime.RequiredError(
                'consentId',
                'Required parameter "consentId" was null or undefined when calling getBalances().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getBalances().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/consents/{consentId}/accounts/{accountId}/balances`;
        urlPath = urlPath.replace('{consentId}', encodeURIComponent(String(requestParameters['consentId'])));
        urlPath = urlPath.replace('{accountId}', encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get balances for an account
     */
    async getBalancesRaw(requestParameters: GetBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Balance>>> {
        const requestOptions = await this.getBalancesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BalanceFromJSON));
    }

    /**
     * Get balances for an account
     */
    async getBalances(requestParameters: GetBalancesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Balance>> {
        const response = await this.getBalancesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTransactions without sending the request
     */
    async getTransactionsRequestOpts(requestParameters: GetTransactionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['consentId'] == null) {
            throw new runtime.RequiredError(
                'consentId',
                'Required parameter "consentId" was null or undefined when calling getTransactions().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getTransactions().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageKey'] != null) {
            queryParameters['pageKey'] = requestParameters['pageKey'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/consents/{consentId}/accounts/{accountId}/transactions`;
        urlPath = urlPath.replace('{consentId}', encodeURIComponent(String(requestParameters['consentId'])));
        urlPath = urlPath.replace('{accountId}', encodeURIComponent(String(requestParameters['accountId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get transactions for an account (paginated)
     */
    async getTransactionsRaw(requestParameters: GetTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TransactionPage>> {
        const requestOptions = await this.getTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TransactionPageFromJSON(jsonValue));
    }

    /**
     * Get transactions for an account (paginated)
     */
    async getTransactions(requestParameters: GetTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TransactionPage> {
        const response = await this.getTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAccounts without sending the request
     */
    async listAccountsRequestOpts(requestParameters: ListAccountsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['consentId'] == null) {
            throw new runtime.RequiredError(
                'consentId',
                'Required parameter "consentId" was null or undefined when calling listAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/consents/{consentId}/accounts`;
        urlPath = urlPath.replace('{consentId}', encodeURIComponent(String(requestParameters['consentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List accounts available under an authorised consent
     */
    async listAccountsRaw(requestParameters: ListAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Account>>> {
        const requestOptions = await this.listAccountsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountFromJSON));
    }

    /**
     * List accounts available under an authorised consent
     */
    async listAccounts(requestParameters: ListAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Account>> {
        const response = await this.listAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
