/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Consent,
    ConsentFromJSON,
    ConsentToJSON,
} from '../models/Consent';
import {
    type CreateConsentRequest,
    CreateConsentRequestFromJSON,
    CreateConsentRequestToJSON,
} from '../models/CreateConsentRequest';

export interface AuthorisationCallbackRequest {
    state: string;
    code?: string;
    error?: string;
}

export interface CreateConsentOperationRequest {
    createConsentRequest: CreateConsentRequest;
}

export interface GetConsentRequest {
    consentId: string;
}

/**
 * 
 */
export class ConsentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for authorisationCallback without sending the request
     */
    async authorisationCallbackRequestOpts(requestParameters: AuthorisationCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authorisationCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * OAuth callback the bank redirects the customer to after authorisation
     */
    async authorisationCallbackRaw(requestParameters: AuthorisationCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authorisationCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * OAuth callback the bank redirects the customer to after authorisation
     */
    async authorisationCallback(requestParameters: AuthorisationCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authorisationCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for createConsent without sending the request
     */
    async createConsentRequestOpts(requestParameters: CreateConsentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createConsentRequest'] == null) {
            throw new runtime.RequiredError(
                'createConsentRequest',
                'Required parameter "createConsentRequest" was null or undefined when calling createConsent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/consents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateConsentRequestToJSON(requestParameters['createConsentRequest']),
        };
    }

    /**
     * Create an AIS consent and obtain the bank authorisation URL
     */
    async createConsentRaw(requestParameters: CreateConsentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Consent>> {
        const requestOptions = await this.createConsentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsentFromJSON(jsonValue));
    }

    /**
     * Create an AIS consent and obtain the bank authorisation URL
     */
    async createConsent(requestParameters: CreateConsentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Consent> {
        const response = await this.createConsentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConsent without sending the request
     */
    async getConsentRequestOpts(requestParameters: GetConsentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['consentId'] == null) {
            throw new runtime.RequiredError(
                'consentId',
                'Required parameter "consentId" was null or undefined when calling getConsent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/consents/{consentId}`;
        urlPath = urlPath.replace('{consentId}', encodeURIComponent(String(requestParameters['consentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get consent status
     */
    async getConsentRaw(requestParameters: GetConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Consent>> {
        const requestOptions = await this.getConsentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConsentFromJSON(jsonValue));
    }

    /**
     * Get consent status
     */
    async getConsent(requestParameters: GetConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Consent> {
        const response = await this.getConsentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
