/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreatePaymentRequest,
    CreatePaymentRequestFromJSON,
    CreatePaymentRequestToJSON,
} from '../models/CreatePaymentRequest';
import {
    type Payment,
    PaymentFromJSON,
    PaymentToJSON,
} from '../models/Payment';

export interface CreatePaymentOperationRequest {
    createPaymentRequest: CreatePaymentRequest;
}

export interface GetPaymentRequest {
    paymentId: string;
}

export interface PaymentAuthorisationCallbackRequest {
    state: string;
    code?: string;
    error?: string;
}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPayment without sending the request
     */
    async createPaymentRequestOpts(requestParameters: CreatePaymentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createPaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'createPaymentRequest',
                'Required parameter "createPaymentRequest" was null or undefined when calling createPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/payments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentRequestToJSON(requestParameters['createPaymentRequest']),
        };
    }

    /**
     * Create a single domestic payment and obtain the bank authorisation URL
     */
    async createPaymentRaw(requestParameters: CreatePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.createPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Create a single domestic payment and obtain the bank authorisation URL
     */
    async createPayment(requestParameters: CreatePaymentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.createPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPayment without sending the request
     */
    async getPaymentRequestOpts(requestParameters: GetPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling getPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/payments/{paymentId}`;
        urlPath = urlPath.replace('{paymentId}', encodeURIComponent(String(requestParameters['paymentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get payment status (refreshes from the provider while in flight)
     */
    async getPaymentRaw(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.getPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Get payment status (refreshes from the provider while in flight)
     */
    async getPayment(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.getPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentAuthorisationCallback without sending the request
     */
    async paymentAuthorisationCallbackRequestOpts(requestParameters: PaymentAuthorisationCallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling paymentAuthorisationCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/payments/callback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * OAuth callback for payment authorisation journeys
     */
    async paymentAuthorisationCallbackRaw(requestParameters: PaymentAuthorisationCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.paymentAuthorisationCallbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * OAuth callback for payment authorisation journeys
     */
    async paymentAuthorisationCallback(requestParameters: PaymentAuthorisationCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentAuthorisationCallbackRaw(requestParameters, initOverrides);
    }

}
