/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateWebhookSubscriptionRequest,
    CreateWebhookSubscriptionRequestFromJSON,
    CreateWebhookSubscriptionRequestToJSON,
} from '../models/CreateWebhookSubscriptionRequest';
import {
    type WebhookSubscription,
    WebhookSubscriptionFromJSON,
    WebhookSubscriptionToJSON,
} from '../models/WebhookSubscription';

export interface CreateWebhookSubscriptionOperationRequest {
    createWebhookSubscriptionRequest: CreateWebhookSubscriptionRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates request options for createWebhookSubscription without sending the request
     */
    async createWebhookSubscriptionRequestOpts(requestParameters: CreateWebhookSubscriptionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createWebhookSubscriptionRequest'] == null) {
            throw new runtime.RequiredError(
                'createWebhookSubscriptionRequest',
                'Required parameter "createWebhookSubscriptionRequest" was null or undefined when calling createWebhookSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhooks`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookSubscriptionRequestToJSON(requestParameters['createWebhookSubscriptionRequest']),
        };
    }

    /**
     * Register a webhook endpoint for payment events
     */
    async createWebhookSubscriptionRaw(requestParameters: CreateWebhookSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookSubscription>> {
        const requestOptions = await this.createWebhookSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookSubscriptionFromJSON(jsonValue));
    }

    /**
     * Register a webhook endpoint for payment events
     */
    async createWebhookSubscription(requestParameters: CreateWebhookSubscriptionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookSubscription> {
        const response = await this.createWebhookSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listWebhookSubscriptions without sending the request
     */
    async listWebhookSubscriptionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/webhooks`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List webhook subscriptions (secrets never returned)
     */
    async listWebhookSubscriptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebhookSubscription>>> {
        const requestOptions = await this.listWebhookSubscriptionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebhookSubscriptionFromJSON));
    }

    /**
     * List webhook subscriptions (secrets never returned)
     */
    async listWebhookSubscriptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebhookSubscription>> {
        const response = await this.listWebhookSubscriptionsRaw(initOverrides);
        return await response.value();
    }

}
