/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountIdentifiersInner
 */
export interface AccountIdentifiersInner {
    /**
     * 
     * @type {string}
     * @memberof AccountIdentifiersInner
     */
    scheme?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountIdentifiersInner
     */
    identification?: string;
}

/**
 * Check if a given object implements the AccountIdentifiersInner interface.
 */
export function instanceOfAccountIdentifiersInner(value: object): value is AccountIdentifiersInner {
    return true;
}

export function AccountIdentifiersInnerFromJSON(json: any): AccountIdentifiersInner {
    return AccountIdentifiersInnerFromJSONTyped(json, false);
}

export function AccountIdentifiersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountIdentifiersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'identification': json['identification'] == null ? undefined : json['identification'],
    };
}

export function AccountIdentifiersInnerToJSON(json: any): AccountIdentifiersInner {
    return AccountIdentifiersInnerToJSONTyped(json, false);
}

export function AccountIdentifiersInnerToJSONTyped(value?: AccountIdentifiersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scheme': value['scheme'],
        'identification': value['identification'],
    };
}

