/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountIdentifiersInner } from './AccountIdentifiersInner';
import {
    AccountIdentifiersInnerFromJSON,
    AccountIdentifiersInnerFromJSONTyped,
    AccountIdentifiersInnerToJSON,
    AccountIdentifiersInnerToJSONTyped,
} from './AccountIdentifiersInner';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    currency: string;
    /**
     * 
     * @type {AccountTypeEnum}
     * @memberof Account
     */
    type: AccountTypeEnum;
    /**
     * 
     * @type {Array<AccountIdentifiersInner>}
     * @memberof Account
     */
    identifiers?: Array<AccountIdentifiersInner>;
}


/**
 * @export
 */
export const AccountTypeEnum = {
    Current: 'CURRENT',
    Savings: 'SAVINGS',
    CreditCard: 'CREDIT_CARD',
    Other: 'OTHER'
} as const;
export type AccountTypeEnum = typeof AccountTypeEnum[keyof typeof AccountTypeEnum];


/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'nickname': json['nickname'],
        'currency': json['currency'],
        'type': json['type'],
        'identifiers': json['identifiers'] == null ? undefined : ((json['identifiers'] as Array<any>).map(AccountIdentifiersInnerFromJSON)),
    };
}

export function AccountToJSON(json: any): Account {
    return AccountToJSONTyped(json, false);
}

export function AccountToJSONTyped(value?: Account | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'nickname': value['nickname'],
        'currency': value['currency'],
        'type': value['type'],
        'identifiers': value['identifiers'] == null ? undefined : ((value['identifiers'] as Array<any>).map(AccountIdentifiersInnerToJSON)),
    };
}

