/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Balance
 */
export interface Balance {
    /**
     * 
     * @type {string}
     * @memberof Balance
     */
    accountId: string;
    /**
     * 
     * @type {BalanceTypeEnum}
     * @memberof Balance
     */
    type: BalanceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Balance
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Balance
     */
    currency: string;
    /**
     * 
     * @type {Date}
     * @memberof Balance
     */
    timestamp: Date;
}


/**
 * @export
 */
export const BalanceTypeEnum = {
    Current: 'CURRENT',
    Available: 'AVAILABLE'
} as const;
export type BalanceTypeEnum = typeof BalanceTypeEnum[keyof typeof BalanceTypeEnum];


/**
 * Check if a given object implements the Balance interface.
 */
export function instanceOfBalance(value: object): value is Balance {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function BalanceFromJSON(json: any): Balance {
    return BalanceFromJSONTyped(json, false);
}

export function BalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Balance {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'type': json['type'],
        'amount': json['amount'],
        'currency': json['currency'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function BalanceToJSON(json: any): Balance {
    return BalanceToJSONTyped(json, false);
}

export function BalanceToJSONTyped(value?: Balance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'type': value['type'],
        'amount': value['amount'],
        'currency': value['currency'],
        'timestamp': value['timestamp'].toISOString(),
    };
}

