/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Consent
 */
export interface Consent {
    /**
     * 
     * @type {string}
     * @memberof Consent
     */
    consentId: string;
    /**
     * 
     * @type {string}
     * @memberof Consent
     */
    providerId: string;
    /**
     * 
     * @type {ConsentStatusEnum}
     * @memberof Consent
     */
    status: ConsentStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Consent
     */
    permissions: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Consent
     */
    expiresAt: Date;
    /**
     * Present on creation only — where to send the customer to authorise
     * @type {string}
     * @memberof Consent
     */
    authorisationUrl?: string | null;
}


/**
 * @export
 */
export const ConsentStatusEnum = {
    AwaitingAuthorisation: 'AWAITING_AUTHORISATION',
    Authorised: 'AUTHORISED',
    Rejected: 'REJECTED',
    Revoked: 'REVOKED',
    Expired: 'EXPIRED'
} as const;
export type ConsentStatusEnum = typeof ConsentStatusEnum[keyof typeof ConsentStatusEnum];


/**
 * Check if a given object implements the Consent interface.
 */
export function instanceOfConsent(value: object): value is Consent {
    if (!('consentId' in value) || value['consentId'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function ConsentFromJSON(json: any): Consent {
    return ConsentFromJSONTyped(json, false);
}

export function ConsentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Consent {
    if (json == null) {
        return json;
    }
    return {
        
        'consentId': json['consentId'],
        'providerId': json['providerId'],
        'status': json['status'],
        'permissions': json['permissions'],
        'expiresAt': (new Date(json['expiresAt'])),
        'authorisationUrl': json['authorisationUrl'] == null ? undefined : json['authorisationUrl'],
    };
}

export function ConsentToJSON(json: any): Consent {
    return ConsentToJSONTyped(json, false);
}

export function ConsentToJSONTyped(value?: Consent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'consentId': value['consentId'],
        'providerId': value['providerId'],
        'status': value['status'],
        'permissions': value['permissions'],
        'expiresAt': value['expiresAt'].toISOString(),
        'authorisationUrl': value['authorisationUrl'],
    };
}

