/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatePaymentRequestCreditor } from './CreatePaymentRequestCreditor';
import {
    CreatePaymentRequestCreditorFromJSON,
    CreatePaymentRequestCreditorFromJSONTyped,
    CreatePaymentRequestCreditorToJSON,
    CreatePaymentRequestCreditorToJSONTyped,
} from './CreatePaymentRequestCreditor';

/**
 * 
 * @export
 * @interface CreatePaymentRequest
 */
export interface CreatePaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    providerId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    currency: string;
    /**
     * 
     * @type {CreatePaymentRequestCreditor}
     * @memberof CreatePaymentRequest
     */
    creditor: CreatePaymentRequestCreditor;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    reference: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequest
     */
    redirectUri: string;
}

/**
 * Check if a given object implements the CreatePaymentRequest interface.
 */
export function instanceOfCreatePaymentRequest(value: object): value is CreatePaymentRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('creditor' in value) || value['creditor'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function CreatePaymentRequestFromJSON(json: any): CreatePaymentRequest {
    return CreatePaymentRequestFromJSONTyped(json, false);
}

export function CreatePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'creditor': CreatePaymentRequestCreditorFromJSON(json['creditor']),
        'reference': json['reference'],
        'redirectUri': json['redirectUri'],
    };
}

export function CreatePaymentRequestToJSON(json: any): CreatePaymentRequest {
    return CreatePaymentRequestToJSONTyped(json, false);
}

export function CreatePaymentRequestToJSONTyped(value?: CreatePaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'creditor': CreatePaymentRequestCreditorToJSON(value['creditor']),
        'reference': value['reference'],
        'redirectUri': value['redirectUri'],
    };
}

