/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConsentRequest
 */
export interface CreateConsentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateConsentRequest
     */
    providerId: string;
    /**
     * 
     * @type {Array<CreateConsentRequestPermissionsEnum>}
     * @memberof CreateConsentRequest
     */
    permissions: Array<CreateConsentRequestPermissionsEnum>;
    /**
     * Where the customer is sent after the platform completes the callback
     * @type {string}
     * @memberof CreateConsentRequest
     */
    redirectUri: string;
}


/**
 * @export
 */
export const CreateConsentRequestPermissionsEnum = {
    ReadAccounts: 'READ_ACCOUNTS',
    ReadBalances: 'READ_BALANCES',
    ReadTransactions: 'READ_TRANSACTIONS',
    ReadIdentity: 'READ_IDENTITY'
} as const;
export type CreateConsentRequestPermissionsEnum = typeof CreateConsentRequestPermissionsEnum[keyof typeof CreateConsentRequestPermissionsEnum];


/**
 * Check if a given object implements the CreateConsentRequest interface.
 */
export function instanceOfCreateConsentRequest(value: object): value is CreateConsentRequest {
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function CreateConsentRequestFromJSON(json: any): CreateConsentRequest {
    return CreateConsentRequestFromJSONTyped(json, false);
}

export function CreateConsentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConsentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'providerId': json['providerId'],
        'permissions': json['permissions'],
        'redirectUri': json['redirectUri'],
    };
}

export function CreateConsentRequestToJSON(json: any): CreateConsentRequest {
    return CreateConsentRequestToJSONTyped(json, false);
}

export function CreateConsentRequestToJSONTyped(value?: CreateConsentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'providerId': value['providerId'],
        'permissions': value['permissions'],
        'redirectUri': value['redirectUri'],
    };
}

