/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentRequestCreditor
 */
export interface CreatePaymentRequestCreditor {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestCreditor
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestCreditor
     */
    scheme: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentRequestCreditor
     */
    identification: string;
}

/**
 * Check if a given object implements the CreatePaymentRequestCreditor interface.
 */
export function instanceOfCreatePaymentRequestCreditor(value: object): value is CreatePaymentRequestCreditor {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('scheme' in value) || value['scheme'] === undefined) return false;
    if (!('identification' in value) || value['identification'] === undefined) return false;
    return true;
}

export function CreatePaymentRequestCreditorFromJSON(json: any): CreatePaymentRequestCreditor {
    return CreatePaymentRequestCreditorFromJSONTyped(json, false);
}

export function CreatePaymentRequestCreditorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentRequestCreditor {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'scheme': json['scheme'],
        'identification': json['identification'],
    };
}

export function CreatePaymentRequestCreditorToJSON(json: any): CreatePaymentRequestCreditor {
    return CreatePaymentRequestCreditorToJSONTyped(json, false);
}

export function CreatePaymentRequestCreditorToJSONTyped(value?: CreatePaymentRequestCreditor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'scheme': value['scheme'],
        'identification': value['identification'],
    };
}

