/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookSubscriptionRequest
 */
export interface CreateWebhookSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookSubscriptionRequest
     */
    url: string;
    /**
     * Signs each delivery (HMAC-SHA256 over the raw body, sent as X-Yapilayer-Signature sha256=hex)
     * @type {string}
     * @memberof CreateWebhookSubscriptionRequest
     */
    secret: string;
}

/**
 * Check if a given object implements the CreateWebhookSubscriptionRequest interface.
 */
export function instanceOfCreateWebhookSubscriptionRequest(value: object): value is CreateWebhookSubscriptionRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function CreateWebhookSubscriptionRequestFromJSON(json: any): CreateWebhookSubscriptionRequest {
    return CreateWebhookSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateWebhookSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'secret': json['secret'],
    };
}

export function CreateWebhookSubscriptionRequestToJSON(json: any): CreateWebhookSubscriptionRequest {
    return CreateWebhookSubscriptionRequestToJSONTyped(json, false);
}

export function CreateWebhookSubscriptionRequestToJSONTyped(value?: CreateWebhookSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'secret': value['secret'],
    };
}

