/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    paymentId: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    providerId: string;
    /**
     * 
     * @type {PaymentStatusEnum}
     * @memberof Payment
     */
    status: PaymentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    creditorName: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    reference: string;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Payment
     */
    updatedAt?: Date;
    /**
     * Present on creation only
     * @type {string}
     * @memberof Payment
     */
    authorisationUrl?: string | null;
}


/**
 * @export
 */
export const PaymentStatusEnum = {
    Pending: 'PENDING',
    Authorised: 'AUTHORISED',
    Rejected: 'REJECTED',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;
export type PaymentStatusEnum = typeof PaymentStatusEnum[keyof typeof PaymentStatusEnum];


/**
 * Check if a given object implements the Payment interface.
 */
export function instanceOfPayment(value: object): value is Payment {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('providerId' in value) || value['providerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('creditorName' in value) || value['creditorName'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function PaymentFromJSON(json: any): Payment {
    return PaymentFromJSONTyped(json, false);
}

export function PaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Payment {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'providerId': json['providerId'],
        'status': json['status'],
        'amount': json['amount'],
        'currency': json['currency'],
        'creditorName': json['creditorName'],
        'reference': json['reference'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'authorisationUrl': json['authorisationUrl'] == null ? undefined : json['authorisationUrl'],
    };
}

export function PaymentToJSON(json: any): Payment {
    return PaymentToJSONTyped(json, false);
}

export function PaymentToJSONTyped(value?: Payment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
        'providerId': value['providerId'],
        'status': value['status'],
        'amount': value['amount'],
        'currency': value['currency'],
        'creditorName': value['creditorName'],
        'reference': value['reference'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'authorisationUrl': value['authorisationUrl'],
    };
}

