/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Provider
 */
export interface Provider {
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Provider
     */
    name: string;
    /**
     * ISO 3166-1 alpha-2
     * @type {string}
     * @memberof Provider
     */
    country: string;
    /**
     * 
     * @type {Array<ProviderCapabilitiesEnum>}
     * @memberof Provider
     */
    capabilities: Array<ProviderCapabilitiesEnum>;
}


/**
 * @export
 */
export const ProviderCapabilitiesEnum = {
    Ais: 'AIS',
    Pis: 'PIS',
    Cop: 'COP',
    Vrp: 'VRP'
} as const;
export type ProviderCapabilitiesEnum = typeof ProviderCapabilitiesEnum[keyof typeof ProviderCapabilitiesEnum];


/**
 * Check if a given object implements the Provider interface.
 */
export function instanceOfProvider(value: object): value is Provider {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('capabilities' in value) || value['capabilities'] === undefined) return false;
    return true;
}

export function ProviderFromJSON(json: any): Provider {
    return ProviderFromJSONTyped(json, false);
}

export function ProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Provider {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'country': json['country'],
        'capabilities': json['capabilities'],
    };
}

export function ProviderToJSON(json: any): Provider {
    return ProviderToJSONTyped(json, false);
}

export function ProviderToJSONTyped(value?: Provider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country': value['country'],
        'capabilities': value['capabilities'],
    };
}

