/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    amount: string;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    currency: string;
    /**
     * 
     * @type {TransactionStatusEnum}
     * @memberof Transaction
     */
    status: TransactionStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    bookingDate: Date;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    reference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    merchantName?: string | null;
}


/**
 * @export
 */
export const TransactionStatusEnum = {
    Booked: 'BOOKED',
    Pending: 'PENDING'
} as const;
export type TransactionStatusEnum = typeof TransactionStatusEnum[keyof typeof TransactionStatusEnum];


/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('bookingDate' in value) || value['bookingDate'] === undefined) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': json['status'],
        'bookingDate': (new Date(json['bookingDate'])),
        'reference': json['reference'] == null ? undefined : json['reference'],
        'merchantName': json['merchantName'] == null ? undefined : json['merchantName'],
    };
}

export function TransactionToJSON(json: any): Transaction {
    return TransactionToJSONTyped(json, false);
}

export function TransactionToJSONTyped(value?: Transaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'bookingDate': value['bookingDate'].toISOString().substring(0,10),
        'reference': value['reference'],
        'merchantName': value['merchantName'],
    };
}

