/* tslint:disable */
/* eslint-disable */
/**
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * 
 * @export
 * @interface TransactionPage
 */
export interface TransactionPage {
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof TransactionPage
     */
    transactions: Array<Transaction>;
    /**
     * 
     * @type {string}
     * @memberof TransactionPage
     */
    nextPageKey?: string | null;
}

/**
 * Check if a given object implements the TransactionPage interface.
 */
export function instanceOfTransactionPage(value: object): value is TransactionPage {
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function TransactionPageFromJSON(json: any): TransactionPage {
    return TransactionPageFromJSONTyped(json, false);
}

export function TransactionPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionPage {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
        'nextPageKey': json['nextPageKey'] == null ? undefined : json['nextPageKey'],
    };
}

export function TransactionPageToJSON(json: any): TransactionPage {
    return TransactionPageToJSONTyped(json, false);
}

export function TransactionPageToJSONTyped(value?: TransactionPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactions': ((value['transactions'] as Array<any>).map(TransactionToJSON)),
        'nextPageKey': value['nextPageKey'],
    };
}

