/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Consent
 */
class ConsentTest {
    private final Consent model = new Consent();

    /**
     * Model tests for Consent
     */
    @Test
    void testConsent() {
        // TODO: test Consent
    }

    /**
     * Test the property 'consentId'
     */
    @Test
    void consentIdTest() {
        // TODO: test consentId
    }

    /**
     * Test the property 'providerId'
     */
    @Test
    void providerIdTest() {
        // TODO: test providerId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    void expiresAtTest() {
        // TODO: test expiresAt
    }

    /**
     * Test the property 'authorisationUrl'
     */
    @Test
    void authorisationUrlTest() {
        // TODO: test authorisationUrl
    }

}
