/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePaymentRequestCreditor
 */
class CreatePaymentRequestCreditorTest {
    private final CreatePaymentRequestCreditor model = new CreatePaymentRequestCreditor();

    /**
     * Model tests for CreatePaymentRequestCreditor
     */
    @Test
    void testCreatePaymentRequestCreditor() {
        // TODO: test CreatePaymentRequestCreditor
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'scheme'
     */
    @Test
    void schemeTest() {
        // TODO: test scheme
    }

    /**
     * Test the property 'identification'
     */
    @Test
    void identificationTest() {
        // TODO: test identification
    }

}
