/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import org.openapitools.client.model.Account;
import org.openapitools.client.model.Balance;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.TransactionPage;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class AccountsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public AccountsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AccountsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get balances for an account
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @return List&lt;Balance&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Balance> getBalances(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId) throws ApiException {
    return getBalances(consentId, accountId, null);
  }

  /**
   * Get balances for an account
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;Balance&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Balance> getBalances(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Balance>> localVarResponse = getBalancesWithHttpInfo(consentId, accountId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get balances for an account
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @return ApiResponse&lt;List&lt;Balance&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Balance>> getBalancesWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId) throws ApiException {
    return getBalancesWithHttpInfo(consentId, accountId, null);
  }

  /**
   * Get balances for an account
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Balance&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Balance>> getBalancesWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getBalancesRequestBuilder(consentId, accountId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getBalances", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Balance>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Balance> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Balance>>() {});
        

        return new ApiResponse<List<Balance>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getBalancesRequestBuilder(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'consentId' is set
    if (consentId == null) {
      throw new ApiException(400, "Missing the required parameter 'consentId' when calling getBalances");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling getBalances");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/consents/{consentId}/accounts/{accountId}/balances"
        .replace("{consentId}", ApiClient.urlEncode(consentId.toString()))
        .replace("{accountId}", ApiClient.urlEncode(accountId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get transactions for an account (paginated)
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param pageKey  (optional)
   * @param pageSize  (optional, default to 50)
   * @return TransactionPage
   * @throws ApiException if fails to make API call
   */
  public TransactionPage getTransactions(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, @jakarta.annotation.Nullable String pageKey, @jakarta.annotation.Nullable Integer pageSize) throws ApiException {
    return getTransactions(consentId, accountId, pageKey, pageSize, null);
  }

  /**
   * Get transactions for an account (paginated)
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param pageKey  (optional)
   * @param pageSize  (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return TransactionPage
   * @throws ApiException if fails to make API call
   */
  public TransactionPage getTransactions(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, @jakarta.annotation.Nullable String pageKey, @jakarta.annotation.Nullable Integer pageSize, Map<String, String> headers) throws ApiException {
    ApiResponse<TransactionPage> localVarResponse = getTransactionsWithHttpInfo(consentId, accountId, pageKey, pageSize, headers);
    return localVarResponse.getData();
  }

  /**
   * Get transactions for an account (paginated)
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param pageKey  (optional)
   * @param pageSize  (optional, default to 50)
   * @return ApiResponse&lt;TransactionPage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TransactionPage> getTransactionsWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, @jakarta.annotation.Nullable String pageKey, @jakarta.annotation.Nullable Integer pageSize) throws ApiException {
    return getTransactionsWithHttpInfo(consentId, accountId, pageKey, pageSize, null);
  }

  /**
   * Get transactions for an account (paginated)
   * 
   * @param consentId  (required)
   * @param accountId  (required)
   * @param pageKey  (optional)
   * @param pageSize  (optional, default to 50)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TransactionPage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TransactionPage> getTransactionsWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, @jakarta.annotation.Nullable String pageKey, @jakarta.annotation.Nullable Integer pageSize, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTransactionsRequestBuilder(consentId, accountId, pageKey, pageSize, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTransactions", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<TransactionPage>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        TransactionPage responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TransactionPage>() {});
        

        return new ApiResponse<TransactionPage>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTransactionsRequestBuilder(@jakarta.annotation.Nonnull UUID consentId, @jakarta.annotation.Nonnull String accountId, @jakarta.annotation.Nullable String pageKey, @jakarta.annotation.Nullable Integer pageSize, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'consentId' is set
    if (consentId == null) {
      throw new ApiException(400, "Missing the required parameter 'consentId' when calling getTransactions");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling getTransactions");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/consents/{consentId}/accounts/{accountId}/transactions"
        .replace("{consentId}", ApiClient.urlEncode(consentId.toString()))
        .replace("{accountId}", ApiClient.urlEncode(accountId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "pageKey";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("pageKey", pageKey));
    localVarQueryParameterBaseName = "pageSize";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("pageSize", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List accounts available under an authorised consent
   * 
   * @param consentId  (required)
   * @return List&lt;Account&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Account> listAccounts(@jakarta.annotation.Nonnull UUID consentId) throws ApiException {
    return listAccounts(consentId, null);
  }

  /**
   * List accounts available under an authorised consent
   * 
   * @param consentId  (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;Account&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Account> listAccounts(@jakarta.annotation.Nonnull UUID consentId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<Account>> localVarResponse = listAccountsWithHttpInfo(consentId, headers);
    return localVarResponse.getData();
  }

  /**
   * List accounts available under an authorised consent
   * 
   * @param consentId  (required)
   * @return ApiResponse&lt;List&lt;Account&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Account>> listAccountsWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId) throws ApiException {
    return listAccountsWithHttpInfo(consentId, null);
  }

  /**
   * List accounts available under an authorised consent
   * 
   * @param consentId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;Account&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Account>> listAccountsWithHttpInfo(@jakarta.annotation.Nonnull UUID consentId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listAccountsRequestBuilder(consentId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listAccounts", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<Account>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<Account> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<Account>>() {});
        

        return new ApiResponse<List<Account>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listAccountsRequestBuilder(@jakarta.annotation.Nonnull UUID consentId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'consentId' is set
    if (consentId == null) {
      throw new ApiException(400, "Missing the required parameter 'consentId' when calling listAccounts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/consents/{consentId}/accounts"
        .replace("{consentId}", ApiClient.urlEncode(consentId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
