/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Account;
import org.openapitools.client.model.Balance;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.TransactionPage;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Get balances for an account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBalancesTest() throws ApiException {
        UUID consentId = null;
        String accountId = null;
        List<Balance> response = 
        api.getBalances(consentId, accountId);
        
        // TODO: test validations
    }
    
    /**
     * Get transactions for an account (paginated)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTransactionsTest() throws ApiException {
        UUID consentId = null;
        String accountId = null;
        String pageKey = null;
        Integer pageSize = null;
        TransactionPage response = 
        api.getTransactions(consentId, accountId, pageKey, pageSize);
        
        // TODO: test validations
    }
    
    /**
     * List accounts available under an authorised consent
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountsTest() throws ApiException {
        UUID consentId = null;
        List<Account> response = 
        api.listAccounts(consentId);
        
        // TODO: test validations
    }
    
}
