/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Consent;
import org.openapitools.client.model.CreateConsentRequest;
import org.openapitools.client.model.Error;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ConsentsApi
 */
@Disabled
public class ConsentsApiTest {

    private final ConsentsApi api = new ConsentsApi();

    
    /**
     * OAuth callback the bank redirects the customer to after authorisation
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorisationCallbackTest() throws ApiException {
        String state = null;
        String code = null;
        String error = null;
        
        api.authorisationCallback(state, code, error);
        
        // TODO: test validations
    }
    
    /**
     * Create an AIS consent and obtain the bank authorisation URL
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createConsentTest() throws ApiException {
        CreateConsentRequest createConsentRequest = null;
        Consent response = 
        api.createConsent(createConsentRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get consent status
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getConsentTest() throws ApiException {
        UUID consentId = null;
        Consent response = 
        api.getConsent(consentId);
        
        // TODO: test validations
    }
    
}
