/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreatePaymentRequest;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Payment;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    
    /**
     * Create a single domestic payment and obtain the bank authorisation URL
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPaymentTest() throws ApiException {
        CreatePaymentRequest createPaymentRequest = null;
        Payment response = 
        api.createPayment(createPaymentRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get payment status (refreshes from the provider while in flight)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentTest() throws ApiException {
        UUID paymentId = null;
        Payment response = 
        api.getPayment(paymentId);
        
        // TODO: test validations
    }
    
    /**
     * OAuth callback for payment authorisation journeys
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paymentAuthorisationCallbackTest() throws ApiException {
        String state = null;
        String code = null;
        String error = null;
        
        api.paymentAuthorisationCallback(state, code, error);
        
        // TODO: test validations
    }
    
}
