/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateWebhookSubscriptionRequest;
import org.openapitools.client.model.WebhookSubscription;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for WebhooksApi
 */
@Disabled
public class WebhooksApiTest {

    private final WebhooksApi api = new WebhooksApi();

    
    /**
     * Register a webhook endpoint for payment events
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWebhookSubscriptionTest() throws ApiException {
        CreateWebhookSubscriptionRequest createWebhookSubscriptionRequest = null;
        WebhookSubscription response = 
        api.createWebhookSubscription(createWebhookSubscriptionRequest);
        
        // TODO: test validations
    }
    
    /**
     * List webhook subscriptions (secrets never returned)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listWebhookSubscriptionsTest() throws ApiException {
        List<WebhookSubscription> response = 
        api.listWebhookSubscriptions();
        
        // TODO: test validations
    }
    
}
