/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountIdentifiersInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Account
 */
@JsonPropertyOrder({
  Account.JSON_PROPERTY_ACCOUNT_ID,
  Account.JSON_PROPERTY_NICKNAME,
  Account.JSON_PROPERTY_CURRENCY,
  Account.JSON_PROPERTY_TYPE,
  Account.JSON_PROPERTY_IDENTIFIERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class Account {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @jakarta.annotation.Nonnull
  private String accountId;

  public static final String JSON_PROPERTY_NICKNAME = "nickname";
  @jakarta.annotation.Nonnull
  private String nickname;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    CURRENT(String.valueOf("CURRENT")),
    
    SAVINGS(String.valueOf("SAVINGS")),
    
    CREDIT_CARD(String.valueOf("CREDIT_CARD")),
    
    OTHER(String.valueOf("OTHER"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_IDENTIFIERS = "identifiers";
  @jakarta.annotation.Nullable
  private List<AccountIdentifiersInner> identifiers = new ArrayList<>();

  public Account() { 
  }

  public Account accountId(@jakarta.annotation.Nonnull String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Get accountId
   * @return accountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(@jakarta.annotation.Nonnull String accountId) {
    this.accountId = accountId;
  }


  public Account nickname(@jakarta.annotation.Nonnull String nickname) {
    this.nickname = nickname;
    return this;
  }

  /**
   * Get nickname
   * @return nickname
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NICKNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNickname() {
    return nickname;
  }


  @JsonProperty(value = JSON_PROPERTY_NICKNAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNickname(@jakarta.annotation.Nonnull String nickname) {
    this.nickname = nickname;
  }


  public Account currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Account type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Account identifiers(@jakarta.annotation.Nullable List<AccountIdentifiersInner> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public Account addIdentifiersItem(AccountIdentifiersInner identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

  /**
   * Get identifiers
   * @return identifiers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AccountIdentifiersInner> getIdentifiers() {
    return identifiers;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFIERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentifiers(@jakarta.annotation.Nullable List<AccountIdentifiersInner> identifiers) {
    this.identifiers = identifiers;
  }


  /**
   * Return true if this Account object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.accountId, account.accountId) &&
        Objects.equals(this.nickname, account.nickname) &&
        Objects.equals(this.currency, account.currency) &&
        Objects.equals(this.type, account.type) &&
        Objects.equals(this.identifiers, account.identifiers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, nickname, currency, type, identifiers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountId()))));
    }

    // add `nickname` to the URL query string
    if (getNickname() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snickname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNickname()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    // add `identifiers` to the URL query string
    if (getIdentifiers() != null) {
      for (int i = 0; i < getIdentifiers().size(); i++) {
        if (getIdentifiers().get(i) != null) {
          joiner.add(getIdentifiers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sidentifiers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

