/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * AccountIdentifiersInner
 */
@JsonPropertyOrder({
  AccountIdentifiersInner.JSON_PROPERTY_SCHEME,
  AccountIdentifiersInner.JSON_PROPERTY_IDENTIFICATION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class AccountIdentifiersInner {
  public static final String JSON_PROPERTY_SCHEME = "scheme";
  @jakarta.annotation.Nullable
  private String scheme;

  public static final String JSON_PROPERTY_IDENTIFICATION = "identification";
  @jakarta.annotation.Nullable
  private String identification;

  public AccountIdentifiersInner() { 
  }

  public AccountIdentifiersInner scheme(@jakarta.annotation.Nullable String scheme) {
    this.scheme = scheme;
    return this;
  }

  /**
   * Get scheme
   * @return scheme
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getScheme() {
    return scheme;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheme(@jakarta.annotation.Nullable String scheme) {
    this.scheme = scheme;
  }


  public AccountIdentifiersInner identification(@jakarta.annotation.Nullable String identification) {
    this.identification = identification;
    return this;
  }

  /**
   * Get identification
   * @return identification
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDENTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIdentification() {
    return identification;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentification(@jakarta.annotation.Nullable String identification) {
    this.identification = identification;
  }


  /**
   * Return true if this Account_identifiers_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountIdentifiersInner accountIdentifiersInner = (AccountIdentifiersInner) o;
    return Objects.equals(this.scheme, accountIdentifiersInner.scheme) &&
        Objects.equals(this.identification, accountIdentifiersInner.identification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheme, identification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountIdentifiersInner {\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `scheme` to the URL query string
    if (getScheme() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sscheme%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScheme()))));
    }

    // add `identification` to the URL query string
    if (getIdentification() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sidentification%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdentification()))));
    }

    return joiner.toString();
  }
}

