/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Consent
 */
@JsonPropertyOrder({
  Consent.JSON_PROPERTY_CONSENT_ID,
  Consent.JSON_PROPERTY_PROVIDER_ID,
  Consent.JSON_PROPERTY_STATUS,
  Consent.JSON_PROPERTY_PERMISSIONS,
  Consent.JSON_PROPERTY_EXPIRES_AT,
  Consent.JSON_PROPERTY_AUTHORISATION_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class Consent {
  public static final String JSON_PROPERTY_CONSENT_ID = "consentId";
  @jakarta.annotation.Nonnull
  private UUID consentId;

  public static final String JSON_PROPERTY_PROVIDER_ID = "providerId";
  @jakarta.annotation.Nonnull
  private String providerId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AWAITING_AUTHORISATION(String.valueOf("AWAITING_AUTHORISATION")),
    
    AUTHORISED(String.valueOf("AUTHORISED")),
    
    REJECTED(String.valueOf("REJECTED")),
    
    REVOKED(String.valueOf("REVOKED")),
    
    EXPIRED(String.valueOf("EXPIRED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nonnull
  private List<String> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime expiresAt;

  public static final String JSON_PROPERTY_AUTHORISATION_URL = "authorisationUrl";
  private JsonNullable<URI> authorisationUrl = JsonNullable.<URI>undefined();

  public Consent() { 
  }

  public Consent consentId(@jakarta.annotation.Nonnull UUID consentId) {
    this.consentId = consentId;
    return this;
  }

  /**
   * Get consentId
   * @return consentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getConsentId() {
    return consentId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONSENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConsentId(@jakarta.annotation.Nonnull UUID consentId) {
    this.consentId = consentId;
  }


  public Consent providerId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
    return this;
  }

  /**
   * Get providerId
   * @return providerId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProviderId() {
    return providerId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
  }


  public Consent status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public Consent permissions(@jakarta.annotation.Nonnull List<String> permissions) {
    this.permissions = permissions;
    return this;
  }

  public Consent addPermissionsItem(String permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissions(@jakarta.annotation.Nonnull List<String> permissions) {
    this.permissions = permissions;
  }


  public Consent expiresAt(@jakarta.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRES_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpiresAt(@jakarta.annotation.Nonnull OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public Consent authorisationUrl(@jakarta.annotation.Nullable URI authorisationUrl) {
    this.authorisationUrl = JsonNullable.<URI>of(authorisationUrl);
    return this;
  }

  /**
   * Present on creation only — where to send the customer to authorise
   * @return authorisationUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public URI getAuthorisationUrl() {
        return authorisationUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AUTHORISATION_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<URI> getAuthorisationUrl_JsonNullable() {
    return authorisationUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTHORISATION_URL)
  public void setAuthorisationUrl_JsonNullable(JsonNullable<URI> authorisationUrl) {
    this.authorisationUrl = authorisationUrl;
  }

  public void setAuthorisationUrl(@jakarta.annotation.Nullable URI authorisationUrl) {
    this.authorisationUrl = JsonNullable.<URI>of(authorisationUrl);
  }


  /**
   * Return true if this Consent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Consent consent = (Consent) o;
    return Objects.equals(this.consentId, consent.consentId) &&
        Objects.equals(this.providerId, consent.providerId) &&
        Objects.equals(this.status, consent.status) &&
        Objects.equals(this.permissions, consent.permissions) &&
        Objects.equals(this.expiresAt, consent.expiresAt) &&
        equalsNullable(this.authorisationUrl, consent.authorisationUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(consentId, providerId, status, permissions, expiresAt, hashCodeNullable(authorisationUrl));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Consent {\n");
    sb.append("    consentId: ").append(toIndentedString(consentId)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    authorisationUrl: ").append(toIndentedString(authorisationUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `consentId` to the URL query string
    if (getConsentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sconsentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConsentId()))));
    }

    // add `providerId` to the URL query string
    if (getProviderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `permissions` to the URL query string
    if (getPermissions() != null) {
      for (int i = 0; i < getPermissions().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spermissions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPermissions().get(i)))));
      }
    }

    // add `expiresAt` to the URL query string
    if (getExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpiresAt()))));
    }

    // add `authorisationUrl` to the URL query string
    if (getAuthorisationUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorisationUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorisationUrl()))));
    }

    return joiner.toString();
  }
}

