/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.openapitools.client.model.CreatePaymentRequestCreditor;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * CreatePaymentRequest
 */
@JsonPropertyOrder({
  CreatePaymentRequest.JSON_PROPERTY_PROVIDER_ID,
  CreatePaymentRequest.JSON_PROPERTY_AMOUNT,
  CreatePaymentRequest.JSON_PROPERTY_CURRENCY,
  CreatePaymentRequest.JSON_PROPERTY_CREDITOR,
  CreatePaymentRequest.JSON_PROPERTY_REFERENCE,
  CreatePaymentRequest.JSON_PROPERTY_REDIRECT_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class CreatePaymentRequest {
  public static final String JSON_PROPERTY_PROVIDER_ID = "providerId";
  @jakarta.annotation.Nonnull
  private String providerId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_CREDITOR = "creditor";
  @jakarta.annotation.Nonnull
  private CreatePaymentRequestCreditor creditor;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  @jakarta.annotation.Nonnull
  private String reference;

  public static final String JSON_PROPERTY_REDIRECT_URI = "redirectUri";
  @jakarta.annotation.Nonnull
  private URI redirectUri;

  public CreatePaymentRequest() { 
  }

  public CreatePaymentRequest providerId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
    return this;
  }

  /**
   * Get providerId
   * @return providerId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProviderId() {
    return providerId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
  }


  public CreatePaymentRequest amount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  public CreatePaymentRequest currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public CreatePaymentRequest creditor(@jakarta.annotation.Nonnull CreatePaymentRequestCreditor creditor) {
    this.creditor = creditor;
    return this;
  }

  /**
   * Get creditor
   * @return creditor
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDITOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CreatePaymentRequestCreditor getCreditor() {
    return creditor;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDITOR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditor(@jakarta.annotation.Nonnull CreatePaymentRequestCreditor creditor) {
    this.creditor = creditor;
  }


  public CreatePaymentRequest reference(@jakarta.annotation.Nonnull String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReference() {
    return reference;
  }


  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReference(@jakarta.annotation.Nonnull String reference) {
    this.reference = reference;
  }


  public CreatePaymentRequest redirectUri(@jakarta.annotation.Nonnull URI redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * Get redirectUri
   * @return redirectUri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRedirectUri(@jakarta.annotation.Nonnull URI redirectUri) {
    this.redirectUri = redirectUri;
  }


  /**
   * Return true if this CreatePaymentRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePaymentRequest createPaymentRequest = (CreatePaymentRequest) o;
    return Objects.equals(this.providerId, createPaymentRequest.providerId) &&
        Objects.equals(this.amount, createPaymentRequest.amount) &&
        Objects.equals(this.currency, createPaymentRequest.currency) &&
        Objects.equals(this.creditor, createPaymentRequest.creditor) &&
        Objects.equals(this.reference, createPaymentRequest.reference) &&
        Objects.equals(this.redirectUri, createPaymentRequest.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerId, amount, currency, creditor, reference, redirectUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePaymentRequest {\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    creditor: ").append(toIndentedString(creditor)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `providerId` to the URL query string
    if (getProviderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `creditor` to the URL query string
    if (getCreditor() != null) {
      joiner.add(getCreditor().toUrlQueryString(prefix + "creditor" + suffix));
    }

    // add `reference` to the URL query string
    if (getReference() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreference%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReference()))));
    }

    // add `redirectUri` to the URL query string
    if (getRedirectUri() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sredirectUri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedirectUri()))));
    }

    return joiner.toString();
  }
}

