/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * CreateConsentRequest
 */
@JsonPropertyOrder({
  CreateConsentRequest.JSON_PROPERTY_PROVIDER_ID,
  CreateConsentRequest.JSON_PROPERTY_PERMISSIONS,
  CreateConsentRequest.JSON_PROPERTY_REDIRECT_URI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class CreateConsentRequest {
  public static final String JSON_PROPERTY_PROVIDER_ID = "providerId";
  @jakarta.annotation.Nonnull
  private String providerId;

  /**
   * Gets or Sets permissions
   */
  public enum PermissionsEnum {
    READ_ACCOUNTS(String.valueOf("READ_ACCOUNTS")),
    
    READ_BALANCES(String.valueOf("READ_BALANCES")),
    
    READ_TRANSACTIONS(String.valueOf("READ_TRANSACTIONS")),
    
    READ_IDENTITY(String.valueOf("READ_IDENTITY"));

    private String value;

    PermissionsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PermissionsEnum fromValue(String value) {
      for (PermissionsEnum b : PermissionsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nonnull
  private List<PermissionsEnum> permissions = new ArrayList<>();

  public static final String JSON_PROPERTY_REDIRECT_URI = "redirectUri";
  @jakarta.annotation.Nonnull
  private URI redirectUri;

  public CreateConsentRequest() { 
  }

  public CreateConsentRequest providerId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
    return this;
  }

  /**
   * Get providerId
   * @return providerId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProviderId() {
    return providerId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
  }


  public CreateConsentRequest permissions(@jakarta.annotation.Nonnull List<PermissionsEnum> permissions) {
    this.permissions = permissions;
    return this;
  }

  public CreateConsentRequest addPermissionsItem(PermissionsEnum permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<PermissionsEnum> getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPermissions(@jakarta.annotation.Nonnull List<PermissionsEnum> permissions) {
    this.permissions = permissions;
  }


  public CreateConsentRequest redirectUri(@jakarta.annotation.Nonnull URI redirectUri) {
    this.redirectUri = redirectUri;
    return this;
  }

  /**
   * Where the customer is sent after the platform completes the callback
   * @return redirectUri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getRedirectUri() {
    return redirectUri;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECT_URI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRedirectUri(@jakarta.annotation.Nonnull URI redirectUri) {
    this.redirectUri = redirectUri;
  }


  /**
   * Return true if this CreateConsentRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateConsentRequest createConsentRequest = (CreateConsentRequest) o;
    return Objects.equals(this.providerId, createConsentRequest.providerId) &&
        Objects.equals(this.permissions, createConsentRequest.permissions) &&
        Objects.equals(this.redirectUri, createConsentRequest.redirectUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerId, permissions, redirectUri);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateConsentRequest {\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `providerId` to the URL query string
    if (getProviderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderId()))));
    }

    // add `permissions` to the URL query string
    if (getPermissions() != null) {
      for (int i = 0; i < getPermissions().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spermissions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPermissions().get(i)))));
      }
    }

    // add `redirectUri` to the URL query string
    if (getRedirectUri() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sredirectUri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedirectUri()))));
    }

    return joiner.toString();
  }
}

