/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Payment
 */
@JsonPropertyOrder({
  Payment.JSON_PROPERTY_PAYMENT_ID,
  Payment.JSON_PROPERTY_PROVIDER_ID,
  Payment.JSON_PROPERTY_STATUS,
  Payment.JSON_PROPERTY_AMOUNT,
  Payment.JSON_PROPERTY_CURRENCY,
  Payment.JSON_PROPERTY_CREDITOR_NAME,
  Payment.JSON_PROPERTY_REFERENCE,
  Payment.JSON_PROPERTY_CREATED_AT,
  Payment.JSON_PROPERTY_UPDATED_AT,
  Payment.JSON_PROPERTY_AUTHORISATION_URL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class Payment {
  public static final String JSON_PROPERTY_PAYMENT_ID = "paymentId";
  @jakarta.annotation.Nonnull
  private UUID paymentId;

  public static final String JSON_PROPERTY_PROVIDER_ID = "providerId";
  @jakarta.annotation.Nonnull
  private String providerId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    PENDING(String.valueOf("PENDING")),
    
    AUTHORISED(String.valueOf("AUTHORISED")),
    
    REJECTED(String.valueOf("REJECTED")),
    
    COMPLETED(String.valueOf("COMPLETED")),
    
    CANCELLED(String.valueOf("CANCELLED"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  public static final String JSON_PROPERTY_CREDITOR_NAME = "creditorName";
  @jakarta.annotation.Nonnull
  private String creditorName;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  @jakarta.annotation.Nonnull
  private String reference;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_AUTHORISATION_URL = "authorisationUrl";
  private JsonNullable<URI> authorisationUrl = JsonNullable.<URI>undefined();

  public Payment() { 
  }

  public Payment paymentId(@jakarta.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
    return this;
  }

  /**
   * Get paymentId
   * @return paymentId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPaymentId() {
    return paymentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentId(@jakarta.annotation.Nonnull UUID paymentId) {
    this.paymentId = paymentId;
  }


  public Payment providerId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
    return this;
  }

  /**
   * Get providerId
   * @return providerId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProviderId() {
    return providerId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProviderId(@jakarta.annotation.Nonnull String providerId) {
    this.providerId = providerId;
  }


  public Payment status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public Payment amount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  public Payment currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Payment creditorName(@jakarta.annotation.Nonnull String creditorName) {
    this.creditorName = creditorName;
    return this;
  }

  /**
   * Get creditorName
   * @return creditorName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREDITOR_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCreditorName() {
    return creditorName;
  }


  @JsonProperty(value = JSON_PROPERTY_CREDITOR_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditorName(@jakarta.annotation.Nonnull String creditorName) {
    this.creditorName = creditorName;
  }


  public Payment reference(@jakarta.annotation.Nonnull String reference) {
    this.reference = reference;
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getReference() {
    return reference;
  }


  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReference(@jakarta.annotation.Nonnull String reference) {
    this.reference = reference;
  }


  public Payment createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Payment updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public Payment authorisationUrl(@jakarta.annotation.Nullable URI authorisationUrl) {
    this.authorisationUrl = JsonNullable.<URI>of(authorisationUrl);
    return this;
  }

  /**
   * Present on creation only
   * @return authorisationUrl
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public URI getAuthorisationUrl() {
        return authorisationUrl.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AUTHORISATION_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<URI> getAuthorisationUrl_JsonNullable() {
    return authorisationUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTHORISATION_URL)
  public void setAuthorisationUrl_JsonNullable(JsonNullable<URI> authorisationUrl) {
    this.authorisationUrl = authorisationUrl;
  }

  public void setAuthorisationUrl(@jakarta.annotation.Nullable URI authorisationUrl) {
    this.authorisationUrl = JsonNullable.<URI>of(authorisationUrl);
  }


  /**
   * Return true if this Payment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Payment payment = (Payment) o;
    return Objects.equals(this.paymentId, payment.paymentId) &&
        Objects.equals(this.providerId, payment.providerId) &&
        Objects.equals(this.status, payment.status) &&
        Objects.equals(this.amount, payment.amount) &&
        Objects.equals(this.currency, payment.currency) &&
        Objects.equals(this.creditorName, payment.creditorName) &&
        Objects.equals(this.reference, payment.reference) &&
        Objects.equals(this.createdAt, payment.createdAt) &&
        Objects.equals(this.updatedAt, payment.updatedAt) &&
        equalsNullable(this.authorisationUrl, payment.authorisationUrl);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, providerId, status, amount, currency, creditorName, reference, createdAt, updatedAt, hashCodeNullable(authorisationUrl));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payment {\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    providerId: ").append(toIndentedString(providerId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    creditorName: ").append(toIndentedString(creditorName)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    authorisationUrl: ").append(toIndentedString(authorisationUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paymentId` to the URL query string
    if (getPaymentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spaymentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPaymentId()))));
    }

    // add `providerId` to the URL query string
    if (getProviderId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sproviderId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `creditorName` to the URL query string
    if (getCreditorName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screditorName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreditorName()))));
    }

    // add `reference` to the URL query string
    if (getReference() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreference%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReference()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    // add `authorisationUrl` to the URL query string
    if (getAuthorisationUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorisationUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorisationUrl()))));
    }

    return joiner.toString();
  }
}

