/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * Transaction
 */
@JsonPropertyOrder({
  Transaction.JSON_PROPERTY_TRANSACTION_ID,
  Transaction.JSON_PROPERTY_AMOUNT,
  Transaction.JSON_PROPERTY_CURRENCY,
  Transaction.JSON_PROPERTY_STATUS,
  Transaction.JSON_PROPERTY_BOOKING_DATE,
  Transaction.JSON_PROPERTY_REFERENCE,
  Transaction.JSON_PROPERTY_MERCHANT_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class Transaction {
  public static final String JSON_PROPERTY_TRANSACTION_ID = "transactionId";
  @jakarta.annotation.Nonnull
  private String transactionId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @jakarta.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @jakarta.annotation.Nonnull
  private String currency;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    BOOKED(String.valueOf("BOOKED")),
    
    PENDING(String.valueOf("PENDING"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  public static final String JSON_PROPERTY_BOOKING_DATE = "bookingDate";
  @jakarta.annotation.Nonnull
  private LocalDate bookingDate;

  public static final String JSON_PROPERTY_REFERENCE = "reference";
  private JsonNullable<String> reference = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MERCHANT_NAME = "merchantName";
  private JsonNullable<String> merchantName = JsonNullable.<String>undefined();

  public Transaction() { 
  }

  public Transaction transactionId(@jakarta.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Get transactionId
   * @return transactionId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionId(@jakarta.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public Transaction amount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@jakarta.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  public Transaction currency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurrency() {
    return currency;
  }


  @JsonProperty(value = JSON_PROPERTY_CURRENCY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(@jakarta.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public Transaction status(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public Transaction bookingDate(@jakarta.annotation.Nonnull LocalDate bookingDate) {
    this.bookingDate = bookingDate;
    return this;
  }

  /**
   * Get bookingDate
   * @return bookingDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BOOKING_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LocalDate getBookingDate() {
    return bookingDate;
  }


  @JsonProperty(value = JSON_PROPERTY_BOOKING_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingDate(@jakarta.annotation.Nonnull LocalDate bookingDate) {
    this.bookingDate = bookingDate;
  }


  public Transaction reference(@jakarta.annotation.Nullable String reference) {
    this.reference = JsonNullable.<String>of(reference);
    return this;
  }

  /**
   * Get reference
   * @return reference
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getReference() {
        return reference.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REFERENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReference_JsonNullable() {
    return reference;
  }
  
  @JsonProperty(JSON_PROPERTY_REFERENCE)
  public void setReference_JsonNullable(JsonNullable<String> reference) {
    this.reference = reference;
  }

  public void setReference(@jakarta.annotation.Nullable String reference) {
    this.reference = JsonNullable.<String>of(reference);
  }


  public Transaction merchantName(@jakarta.annotation.Nullable String merchantName) {
    this.merchantName = JsonNullable.<String>of(merchantName);
    return this;
  }

  /**
   * Get merchantName
   * @return merchantName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getMerchantName() {
        return merchantName.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MERCHANT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getMerchantName_JsonNullable() {
    return merchantName;
  }
  
  @JsonProperty(JSON_PROPERTY_MERCHANT_NAME)
  public void setMerchantName_JsonNullable(JsonNullable<String> merchantName) {
    this.merchantName = merchantName;
  }

  public void setMerchantName(@jakarta.annotation.Nullable String merchantName) {
    this.merchantName = JsonNullable.<String>of(merchantName);
  }


  /**
   * Return true if this Transaction object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.transactionId, transaction.transactionId) &&
        Objects.equals(this.amount, transaction.amount) &&
        Objects.equals(this.currency, transaction.currency) &&
        Objects.equals(this.status, transaction.status) &&
        Objects.equals(this.bookingDate, transaction.bookingDate) &&
        equalsNullable(this.reference, transaction.reference) &&
        equalsNullable(this.merchantName, transaction.merchantName);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, amount, currency, status, bookingDate, hashCodeNullable(reference), hashCodeNullable(merchantName));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    bookingDate: ").append(toIndentedString(bookingDate)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    merchantName: ").append(toIndentedString(merchantName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactionId` to the URL query string
    if (getTransactionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stransactionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTransactionId()))));
    }

    // add `amount` to the URL query string
    if (getAmount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmount()))));
    }

    // add `currency` to the URL query string
    if (getCurrency() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scurrency%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurrency()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `bookingDate` to the URL query string
    if (getBookingDate() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbookingDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBookingDate()))));
    }

    // add `reference` to the URL query string
    if (getReference() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreference%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReference()))));
    }

    // add `merchantName` to the URL query string
    if (getMerchantName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smerchantName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMerchantName()))));
    }

    return joiner.toString();
  }
}

