/*
 * Yapilayer API
 * Open-source Open Banking platform API. This specification is the source of truth (spec-first — see ADR 0005): server interfaces and SDKs are generated from this file.  Skeleton at Milestone 0; AIS paths are designed in Milestone 4, PIS paths in Milestone 5, and the spec is finalized in Milestone 7. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Transaction;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * TransactionPage
 */
@JsonPropertyOrder({
  TransactionPage.JSON_PROPERTY_TRANSACTIONS,
  TransactionPage.JSON_PROPERTY_NEXT_PAGE_KEY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-14T18:10:57.288186+01:00[Europe/London]", comments = "Generator version: 7.23.0")
public class TransactionPage {
  public static final String JSON_PROPERTY_TRANSACTIONS = "transactions";
  @jakarta.annotation.Nonnull
  private List<Transaction> transactions = new ArrayList<>();

  public static final String JSON_PROPERTY_NEXT_PAGE_KEY = "nextPageKey";
  private JsonNullable<String> nextPageKey = JsonNullable.<String>undefined();

  public TransactionPage() { 
  }

  public TransactionPage transactions(@jakarta.annotation.Nonnull List<Transaction> transactions) {
    this.transactions = transactions;
    return this;
  }

  public TransactionPage addTransactionsItem(Transaction transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

  /**
   * Get transactions
   * @return transactions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Transaction> getTransactions() {
    return transactions;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactions(@jakarta.annotation.Nonnull List<Transaction> transactions) {
    this.transactions = transactions;
  }


  public TransactionPage nextPageKey(@jakarta.annotation.Nullable String nextPageKey) {
    this.nextPageKey = JsonNullable.<String>of(nextPageKey);
    return this;
  }

  /**
   * Get nextPageKey
   * @return nextPageKey
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getNextPageKey() {
        return nextPageKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_NEXT_PAGE_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNextPageKey_JsonNullable() {
    return nextPageKey;
  }
  
  @JsonProperty(JSON_PROPERTY_NEXT_PAGE_KEY)
  public void setNextPageKey_JsonNullable(JsonNullable<String> nextPageKey) {
    this.nextPageKey = nextPageKey;
  }

  public void setNextPageKey(@jakarta.annotation.Nullable String nextPageKey) {
    this.nextPageKey = JsonNullable.<String>of(nextPageKey);
  }


  /**
   * Return true if this TransactionPage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionPage transactionPage = (TransactionPage) o;
    return Objects.equals(this.transactions, transactionPage.transactions) &&
        equalsNullable(this.nextPageKey, transactionPage.nextPageKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactions, hashCodeNullable(nextPageKey));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionPage {\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    nextPageKey: ").append(toIndentedString(nextPageKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `transactions` to the URL query string
    if (getTransactions() != null) {
      for (int i = 0; i < getTransactions().size(); i++) {
        if (getTransactions().get(i) != null) {
          joiner.add(getTransactions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stransactions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `nextPageKey` to the URL query string
    if (getNextPageKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%snextPageKey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNextPageKey()))));
    }

    return joiner.toString();
  }
}

